FROM golang:1.22-alpine AS builder

WORKDIR /app

# Dependências
COPY go.mod go.sum ./
RUN go mod download

# Código fonte
COPY . .

# Build apontando para o main.go correto
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o api ./cmd/main

# Imagem final
FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /app/api .

EXPOSE 8080

USER nonroot:nonroot

CMD ["./api"]
